sonar.projectKey=notenest
sonar.projectName=NoteNest
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/src/assets/**,**/*.test.js,**/*.test.jsx,**/__mocks__/**,frontend/src/setupTests.js
sonar.tests=backend/test,frontend/src/pages
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info    